-- ─── Soupz Web IDE Schema ─────────────────────────────────────────────────────
-- Run this in your Supabase SQL editor or via supabase db push
-- Keeps tables small: auto-deletes rows older than 1 hour

-- ─── Commands (web → daemon) ──────────────────────────────────────────────────
create table if not exists soupz_commands (
    id          uuid primary key default gen_random_uuid(),
    user_id     uuid not null references auth.users(id) on delete cascade,
    type        text not null,  -- FILE_TREE, FILE_READ, FILE_WRITE, GIT_STATUS, etc.
    payload     jsonb default '{}',
    status      text not null default 'pending',  -- pending | running | done | error
    created_at  timestamptz default now()
);

-- ─── Responses (daemon → web) ─────────────────────────────────────────────────
create table if not exists soupz_responses (
    id          uuid primary key default gen_random_uuid(),
    command_id  uuid references soupz_commands(id) on delete cascade,
    user_id     uuid not null references auth.users(id) on delete cascade,
    type        text not null,
    result      jsonb default '{}',
    status      text not null default 'success',  -- success | error
    created_at  timestamptz default now()
);

-- ─── Pairing (anonymous link) ────────────────────────────────────────────────
-- Allows a phone to find a laptop by a 9-character alphanumeric code without signup.
-- The laptop (daemon) inserts its local IP/metadata here.
-- The phone (web app) reads this to connect.
create table if not exists soupz_pairing (
    code        text primary key, -- 9-character alphanumeric pairing code
    token       text not null,    -- session token generated by daemon
    hostname    text,
    lan_ips     jsonb default '[]',
    public_ip   text,
    port        integer default 7533,
    created_at  timestamptz default now(),
    expires_at  timestamptz not null
);

-- ─── Indexes ──────────────────────────────────────────────────────────────────
create index if not exists idx_commands_user_status  on soupz_commands(user_id, status);
create index if not exists idx_commands_created      on soupz_commands(created_at);
create index if not exists idx_responses_command     on soupz_responses(command_id);
create index if not exists idx_responses_user        on soupz_responses(user_id, created_at);
create index if not exists idx_pairing_expires       on soupz_pairing(expires_at);

-- ─── Row Level Security ───────────────────────────────────────────────────────
alter table soupz_commands  enable row level security;
alter table soupz_responses enable row level security;
alter table soupz_pairing   enable row level security;

-- Users can only see and insert their own commands
create policy "commands: user owns rows" on soupz_commands
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Users can only see their own responses
create policy "responses: user owns rows" on soupz_responses
    for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Pairing rows contain a live session token. They must NOT be world-readable.
--
-- The previous policy was `for select using (true)`, which let anyone holding
-- the public anon key — and that key ships inside the deployed web bundle —
-- dump every active session token for every user of this app. Reads now go
-- through a SECURITY DEFINER function that requires knowing the 9-character
-- code, so a caller can only resolve a pairing they were actually given.
--
-- MIGRATING AN EXISTING DATABASE: run these two statements by hand, then treat
-- every token issued before the change as compromised (they expire on their
-- own, but rotating early costs nothing).
drop policy if exists "pairing: public read" on soupz_pairing;

create or replace function claim_pairing_code(p_code text)
returns table (
    token       text,
    hostname    text,
    lan_ips     jsonb,
    public_ip   text,
    port        integer,
    expires_at  timestamptz
)
language sql
stable
security definer
set search_path = public
as $$
    select p.token, p.hostname, p.lan_ips, p.public_ip, p.port, p.expires_at
    from soupz_pairing p
    where p.code = p_code
      and p.expires_at > now();
$$;

revoke all on function claim_pairing_code(text) from public;
grant execute on function claim_pairing_code(text) to anon, authenticated;

-- Only service role (daemon) can insert/update pairing
-- (RLS defaults to deny for other ops, and there is now no select policy at all)

-- ─── Realtime ─────────────────────────────────────────────────────────────────
-- Enable Realtime for both tables so the daemon receives commands
-- and the web app receives responses in real time
alter publication supabase_realtime add table soupz_commands;
alter publication supabase_realtime add table soupz_responses;
-- soupz_pairing is deliberately NOT published. It holds session tokens, and a
-- realtime stream is one relaxed RLS policy away from broadcasting them.
-- Pairing is a request/response flow; it does not need live subscriptions.
-- If your database already published it, remove it with:
--     alter publication supabase_realtime drop table soupz_pairing;

-- ─── Auto-cleanup: delete rows older than 1 hour (keep free tier small) ───────
create or replace function cleanup_old_soupz_rows() returns void
language plpgsql security definer as $$
begin
    delete from soupz_responses where created_at < now() - interval '1 hour';
    delete from soupz_commands  where created_at < now() - interval '1 hour'
        and status in ('done', 'error');
    delete from soupz_pairing   where expires_at < now();
end;
$$;

-- Run cleanup every hour via pg_cron (enable pg_cron extension in Supabase dashboard first)
-- Uncomment after enabling pg_cron:
-- select cron.schedule('cleanup-soupz', '0 * * * *', 'select cleanup_old_soupz_rows()');

-- ─── Also keep soupz_orders table small ──────────────────────────────────────
-- Existing orders table cleanup (if you have soupz_orders from earlier setup)
create or replace function cleanup_old_orders() returns void
language plpgsql security definer as $$
begin
    delete from soupz_orders where created_at < now() - interval '7 days';
end;
$$;
