-- ─── Commands (web → daemon) ──────────────────────────────────────────────────
create table if not exists public.soupz_commands (
    id          uuid primary key default gen_random_uuid(),
    user_id     uuid references auth.users(id) on delete cascade,
    type        text not null,  -- FILE_TREE, FILE_READ, FILE_WRITE, GIT_STATUS, etc.
    payload     jsonb default '{}',
    status      text not null default 'pending',  -- pending | running | done | error
    created_at  timestamptz default now()
);

-- ─── Responses (daemon → web) ─────────────────────────────────────────────────
create table if not exists public.soupz_responses (
    id          uuid primary key default gen_random_uuid(),
    command_id  uuid references public.soupz_commands(id) on delete cascade,
    user_id     uuid references auth.users(id) on delete cascade,
    type        text not null,
    result      jsonb default '{}',
    status      text not null default 'success',  -- success | error
    created_at  timestamptz default now()
);

-- ─── Pairing (anonymous link) ────────────────────────────────────────────────
create table if not exists public.soupz_pairing (
    code        text primary key, -- 9-character alphanumeric pairing code
    token       text not null,    -- session token generated by daemon
    hostname    text,
    lan_ips     jsonb default '[]',
    public_ip   text,
    port        integer default 7533,
    created_at  timestamptz default now(),
    expires_at  timestamptz not null
);

-- ─── Realtime ─────────────────────────────────────────────────────────────────
alter publication supabase_realtime add table public.soupz_commands;
alter publication supabase_realtime add table public.soupz_responses;
alter publication supabase_realtime add table public.soupz_pairing;
